import os
import glob
import time
import pandas as pd
import google.generativeai as genai
import json

# Directory for permanent rules
RULES_DIR = "rules_storage"
if not os.path.exists(RULES_DIR):
    os.makedirs(RULES_DIR)

def save_permanent_rule(uploaded_file):
    if uploaded_file is not None:
        file_path = os.path.join(RULES_DIR, uploaded_file.name)
        with open(file_path, "wb") as f:
            f.write(uploaded_file.getbuffer())
        return file_path
    return None

def list_saved_rules():
    return [os.path.basename(x) for x in glob.glob(os.path.join(RULES_DIR, "*.pdf"))]

def call_gemini_extraction(api_key, trip_files, context_prompt):
    """
    Uses gemini-3-flash-preview (or pro) to extract data.
    Updated to handle both Streamlit UploadedFiles AND Local File Paths.
    """
    if not api_key:
        return {"error": "No API Key provided"}

    genai.configure(api_key=api_key)
    
    gemini_files = []
    
    # --- 1. Upload Rules/Statutes (Context) ---
    rule_files = glob.glob(os.path.join(RULES_DIR, "*.pdf"))
    for rule_path in rule_files:
        g_file = genai.upload_file(rule_path)
        gemini_files.append(g_file)

    # --- 2. Upload Trip Files (User Documents) ---
    for f in trip_files:
        # CASE A: It is a String (File Path saved in session)
        if isinstance(f, str):
            if os.path.exists(f):
                g_file = genai.upload_file(f)
                gemini_files.append(g_file)
            else:
                return {"error": f"Saved file not found: {f}"}
        
        # CASE B: It is a Streamlit UploadedFile object (Direct upload)
        else:
            # We save it temporarily to upload
            with open(f.name, "wb") as temp_f:
                temp_f.write(f.getbuffer())
            g_file = genai.upload_file(f.name)
            gemini_files.append(g_file)

    time.sleep(2) # Wait for processing

    # --- System Prompt ---
    system_instruction = """
    You are a University Accountant.
    Extract the Tour Diary exactly into the following JSON format.
    
    RETURN JSON ONLY.
    
    JSON Structure:
    {
      "tour_diary": [
        {
          "Departure_Date": "DD-MM-YYYY", 
          "Departure_Time": "HH:MM (24hr)", 
          "Departure_Place": "City/Station Name", 
          "Arrival_Date": "DD-MM-YYYY", 
          "Arrival_Time": "HH:MM (24hr)", 
          "Arrival_Place": "City/Station Name", 
          "Mode_of_Travel": "Bus/Rail/Private Vehicle/University Vehicle (No)/Auto Rickshaw/Flight", 
          "Purpose": "Reason for travel",
          "KM": "Distance in KM (if available, else 0)",
          "Ticket_Price": "Ticket Amount (if available, else 0)"
        }
      ]
    }
    """

    # --- Call Gemini ---
    model = genai.GenerativeModel(
        model_name="gemini-3-flash-preview",
        generation_config={"response_mime_type": "application/json"},
        system_instruction=system_instruction
    )

    try:
        response = model.generate_content([context_prompt, *gemini_files])
        return response.text
    except Exception as e:
        return {"error": str(e)}

# --- Complex Word Doc Generation (Placeholder for Page 6) ---
from docx import Document

def create_complex_claim_form(diary, ta, da):
    doc = Document()
    doc.add_heading('TA/DA Claim Form', 0)
    doc.add_paragraph('Generated by AI Automation')
    # Actual logic will be in your Page 6 or utils if fully implemented
    return doc

